package main.model.request;

public enum RequestType {
    COORDINATOR_ALLOCATE_PROJECT,
    COORDINATOR_APPROVE_REQUEST,
    COORDINATOR_CHANGE_SUPERVISOR,
    COORDINATOR_DEREGISTER_STUDENT,
    STUDENT_REGISTRATION,
    STUDENT_DEREGISTRATION,
    STUDENT_CHANGE_TITLE,
}
